// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwL3x1X7c3gD6LrKQannDblZrgWMZwjws',
    appId: '1:772086656954:web:2746291bd6e4658c8a7783',
    messagingSenderId: '772086656954',
    projectId: 'camera-safe-map',
    authDomain: 'camera-safe-map.firebaseapp.com',
    storageBucket: 'camera-safe-map.firebasestorage.app',
    measurementId: 'G-T1JLQ8MCHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzU6JcQe9jWYub2cXgcSUtz7UnIqD2ioI',
    appId: '1:772086656954:android:0899d408a921a4c68a7783',
    messagingSenderId: '772086656954',
    projectId: 'camera-safe-map',
    storageBucket: 'camera-safe-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WHpO1aehb80rSSmA08nfr62X0d5emCo',
    appId: '1:772086656954:ios:5199d719bab126938a7783',
    messagingSenderId: '772086656954',
    projectId: 'camera-safe-map',
    storageBucket: 'camera-safe-map.firebasestorage.app',
    iosBundleId: 'com.example.camera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5WHpO1aehb80rSSmA08nfr62X0d5emCo',
    appId: '1:772086656954:ios:5199d719bab126938a7783',
    messagingSenderId: '772086656954',
    projectId: 'camera-safe-map',
    storageBucket: 'camera-safe-map.firebasestorage.app',
    iosBundleId: 'com.example.camera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwL3x1X7c3gD6LrKQannDblZrgWMZwjws',
    appId: '1:772086656954:web:9a3e638acc08d3848a7783',
    messagingSenderId: '772086656954',
    projectId: 'camera-safe-map',
    authDomain: 'camera-safe-map.firebaseapp.com',
    storageBucket: 'camera-safe-map.firebasestorage.app',
    measurementId: 'G-V9ZJ6E874S',
  );
}
